Additional type hints and other neatness changes
rorre/Yippi pull request #68
Opened 2021-06-17 14:00 UTC by Deer-Spangle

Sorry, I started this branch with the intention to do more type hints but ended up also changing some other stuff, some bug fixes and some neatness changes

Bug fixes:
- Handling "Content-Type" headers being missing, for example with 204 responses.
- Swapping `file_name` to `file_path` in Post.upload(), as the former doesn't seem to exist

Neatness:
- Swapping remaining string formatting to f-strings
- Switching some stuff to set literals
- Adding `limit` arg to AbstractYippi.flags(), as it was in both implementations
- Chaining some response code checks
- Changing AbstractYippi.notes() `creator_id` argument to an int
- Using public `Enum.value` attribute rather than the `Enum._value_` attribute

If you would rather I broke this into separate pull requests, I can do that.

One question I have is that the aiohttp docs all have responses [handled in context managers](https://docs.aiohttp.org/en/stable/client_quickstart.html#json-response-content). Type hinting things there seemed to go oddly because it expected that, should this library be using responses in that context manager way?

Like, changing this:
```
r = await self._session.request(
    method, url, data=data, headers=self.headers, auth=auth
)
await self._verify_response(r)
if not r.status == 204:
    return await r.json()
```
to this:
```
async with self._session.request(
    method, url, data=data, headers=self.headers, auth=auth
) as r:
    await self._verify_response(r)
    if not r.status == 204:
        return await r.json()
```

2021-06-17 14:18 UTC, rorre commented
Thank you so much for the help!

Regarding context managers--when I wrote it I made the async code to be as similar as sync one. However now that I look at it again, context manager seems to be safer so that the connection properly close.

I don't mind with huge pull request, I'll be glad to look further into it. (Don't mind that there is no CI as of now, somehow docs build is failing on setup--can't tell if it's on my end or something else.)

2021-06-18 06:16 UTC, rorre requested changes
Looks pretty good, just a few stuffs aside from the three in review:
- `AbstractYippi._get_notes()` still have `creator_id` argument type as `str`.
- Run `black` formatter, as the project uses it (needs to be part of CI at some point)

2021-06-18 06:16 UTC, rorre commented on yippi/AbstractYippi.py
> +    def _verify_response(self, r: Union[requests.Response, aiohttp.ClientResponse]) -> None:
Should be `MaybeAwaitable[None]`, as the method is async in `AsyncYippi`.

2021-06-18 06:16 UTC, rorre commented on yippi/AsyncYippi.py
> +    async def _call_api(self, method: str, url: str, data: dict = None, file=None, **kwargs):
Missing type hint `-> Optional[dict]`

2021-06-18 06:16 UTC, rorre commented on yippi/YippiSync.py
> +    def _call_api(self, method: str, url: str, data: dict = None, file=None, **kwargs) -> dict:
Should be `Optional[dict]` as http status code 204 returns nothing.

2021-06-18 11:02 UTC, Deer-Spangle commented on yippi/YippiSync.py
> +    def _call_api(self, method: str, url: str, data: dict = None, file=None, **kwargs) -> dict:
Oh, should be `Optional[Union[List[dict], dict]]` anyway, right? I'll update that

2021-06-18 11:02 UTC, Deer-Spangle commented on yippi/AbstractYippi.py
> +    def _verify_response(self, r: Union[requests.Response, aiohttp.ClientResponse]) -> None:
Oh yes! Updated now

2021-06-18 11:02 UTC, Deer-Spangle commented
There we go, added those changes and ran black, thanks!

2021-06-18 12:32 UTC, merged